---

#- include_tasks: geerlingguy.docker
#  when: ansible_os_family == 'RedHat'
#
#- name: Install Docker Module for Python
#  pip:
#    name: docker
#
#- name: Install Docker Module for Python
#  pip:
#    name: docker-py

- name: pull an image
  docker_image:
    name: noia/agent
    force_source: yes
  tags:
    - pull_agent

- name: Stop and remove old container
  docker_container:
    name: noia-agent
    state: absent
    image: "noia/agent:prod"
  tags:
    - remove_agent

- name: Create agent container and connect to network
  docker_container:
    networks_cli_compatible: yes
    name: noia-agent
    restart_policy: unless-stopped
    image: "noia/agent:{{ stage }}"
    capabilities:
      - NET_ADMIN
      - SYS_MODULE
    networks:
      - name: "host"
    env:
      NOIA_CONTROLLER_URL: "{{ NOIA_CONTROLLER_URL }}"
      NOIA_API_KEY: "{{ NOIA_API_KEY }}"
      NOIA_ALLOWED_IPS: "{{ NOIA_ALLOWED_IPS }}"
      NOIA_NETWORK_API: "{{ NOIA_NETWORK_API }}"
      NOIA_NAME: "{{ NOIA_NAME }}"
      NOIA_COUNTRY: "{{ NOIA_COUNTRY }}"
      NOIA_CITY: "{{ NOIA_CITY }}"
      NOIA_CATEGORY: "{{ NOIA_CATEGORY }}"
      NOIA_PROVIDER: "{{ NOIA_PROVIDER }}"
      NOIA_LAT: "{{ NOIA_LAT }}"
      NOIA_TAGS: "{{ NOIA_TAGS }}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  tags:
    - start_agent